#!/usr/bin/env bash
#Y u no love me

echo "$$" > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo 'I hate the kill command'" SIGTERM
    trap "echo 'Y U no love me?!'" SIGINT
    trap "rm -r /var/run/myscript.pid"  SIGQUIT
done
